### ISSUE TITLE
Unable to install due to dependency version constraint

### ISSUE THREAD

**Issue by TheDigitalOrchard** [ravendb/ravendb-php-client#63]
Hello,

The latest release of this package constraints `symfony/http-client` to `^6.1`, but that package is now at `7.1.*`. Can a fix be pushed, or are there incompatibilities being worked on?

Thanks.

**Comment by alxsabo** [comment]
Hello @TheDigitalOrchard 
We've accepted your merge request to update the Symfony HTTP Client version constraint. Thank you for your contribution.
